[profile.default]
src = "src"
out = "out"
optimizer = true
optimizer_runs = 20_000
solc_version = "0.8.29"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
